//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErdalSuperMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public decimal SalesPrice { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}
