//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLogs
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string Details { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
