//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        public int ProcessedByID { get; set; }
        public System.DateTime ReservationsDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Students Students { get; set; }
        public virtual Users Users { get; set; }
    }
}
